### ISSUE TITLE
randomized view buffer names

### ISSUE THREAD

**Issue by joshsh** [synchrony/smsn#16]
So that entering a new view of an atom doesn't mess up another view of the same atom (with a different configuration and a different point, and possibly with unsaved edits) which you may have open in another window.

Use the atom value as the beginning of the title, include the atom key, and finally tack on a random ID.

Do something similar for search views (the text of the search, followed by a random ID), and for the same reasons... so you can have multiple search views open at the same time.

**Comment by joshsh** [comment]
Closing. If anything, this is a smsn-mode issue.

**Comment by JeffreyBenjaminBrown** [comment]
If the random suffix is finite, which seems likely, then there's some chance of a collision. Why not use the current time instead? Or if we're worried about someone who opens views really fast -- maybe once AI starts using SmSn -- we could use both.

(I realize the chance of a collision is absurdly small.)

**Comment by joshsh** [comment]
Meh. I'm not sure I still want this. Do text editors let you open two separate buffers for the same file? Generally, no. Adds complexity, with the potential of a confusing user experience. Better to have an intelligent way of merging unsaved edits with updates from the server.

**Comment by JeffreyBenjaminBrown** [comment]
I agree.

If views contain important information -- and indeed sometimes they do -- one solution would be to let users save the views as first-class citizens of the graph.

**Comment by joshsh** [comment]
That might be a little weird, but it is entirely possible. There will be a built-in datatype for views, and that datatype will be valid for elements in the graph.
