### ISSUE TITLE
Create Typeatron keying scheme

### ISSUE THREAD

**Issue by joshsh** [synchrony/smsn#28]
5 keys. 17,685 chords.  127 ASCII characters and a few dozen Brain-mode commands.  How will you map them?  Let the madness begin.

**Comment by joshsh** [comment]
Done (long ago).

**Comment by JeffreyBenjaminBrown** [comment]
17,685 chords on 5 keys? I'm counting 31 -- 2 to the power of 5, minus the empty chord. I must not know what you mean by chord.

**Comment by joshsh** [comment]
Chords are order-sensitive, and you can regard key releases as independent
events. From Steve Mann's book [1]: "with only 2 switches, 6 chords are
possible.  With 3 switches, 51 chords are possible.  With 4 switches, 748
chords are possible, and with 5 switches, 17,685 chords are possible."

For example, suppose the keyer has only two keys, A and B. AB and BA are
the two possible chords, in terms of key presses. If you count key
releases, there are 4 chords: ABA'B', ABB'A', BAB'A', BAA'B. By 6, I think
Steve meant to count AA'BB' and BB'AA' as separate chords, as well. Been a
long time.

[1] Mann, S. (2001). Intelligent image processing. John Wiley & Sons, Inc..

**Comment by joshsh** [comment]
Actually, AA' and BB' are the other two chords. 6 is the sum of the number
of two-key chords and the 1-key chords over a set of two keys. AA'BB' would
be a sequence, not a chord.
