### ISSUE TITLE
Proposal: New sharability variety: Classified.

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [synchrony/smsn#38]
Under "skepticism" I wrote the note "the young lack it" (with a citation) and a branch called "how politicians hack(software) voters". I want to share it with every author of the shared graph I am a part of, but there exist people I would rather did not learn (more about) those topics.

(Ideally the user attach sharing (e.g. git) programs to nodes representing subsets of society, and label ideas with those nodes. To reduce the number of edges the graph could automatically construct branch heredity (and heredity exception) representations, conceivably making the graph much smaller than it could be even with property rather than edge shareability. (Haskell makes higher-order programming beautifully concise.) But I'm guessing none of SmSn's few users yet needs an especially elaborate vocabulary for who to share to.)

**Comment by joshsh** [comment]
I actually want to get away from atom-level sharability, and the complexity associated with the sort of filters you describe.  I would much rather allow visibility and access control to be delegated to *datasets*, and assign atoms to datasets.  If a dataset is based on a version-controlled repository, it inherits access control from that repository.  The trick is in combining several datasets as a graph, while keeping the boundaries distinct.  When I create an atom, I need to know which dataset I am adding it to.

In your example, you might have a public dataset you share with the world, and a private dataset you share only with a small set of collaborators.

**Comment by joshsh** [comment]
We now have support for configurable data sources, which enables a "classified" set of notes as proposed in this issue, among many other possibilities.
