### ISSUE TITLE
Text search: And would be a better default than Or.

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [synchrony/smsn#46]
Both are useful -- I frequently run searches like "(graph OR smsn) AND user". But if I just type in some words and don't use either AND or OR, I probably mean to apply AND to them, because OR can easily lead to a slow search.

**Comment by joshsh** [comment]
I feel compelled to link this clip again:
    https://www.youtube.com/watch?v=OUvI5SxeYzU

See:
    https://github.com/synchrony/smsn/commit/8494e80db5b49f331b2b95d21248fdecb1d2a61e
