### ISSUE TITLE
Supporting conflicting ontologies

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [synchrony/smsn#48]
Currently, luckily, the authors of the shared graph at synchrony/data-public and synchrony/data-universal trust each other enough to not be too concerned about filing disagreements. At larger scales, though, it will become tricky. If Author1 wants to file X under Y, and Author2 wants it under Z, we might want a way to allow those two preferences to coexist. A reader could subscribe to one or the other, or program a way to view both when they conflict (e.g. "show both but put mine first and with an asterisk indicating another exists"). A reader might even want to invent their own categories of authors, and rank those author categories, so they don't have to handle each author individually. And we will surely want to handle some kinds of relationships differently than others, even if they were authored by the same person.

I haven't tried to flatten these kinds of relationships; it's probably possible, but I am guessing a high-arity, nested relationships system, ala the RSLT, would make it easier to deal with.

**Comment by joshsh** [comment]
I think this is a little too broad for a GitHub issue, but it is perfect for the [Brainstorming](https://github.com/synchrony/smsn/wiki/Brainstorming) page.  I have moved it there for now.  RSLT in SmSn is definitely of interest, but I think you will need to take the lead on an implementation.

**Comment by joshsh** [comment]
Note: while RSLT are a potential solution, I do see others.  In a shared knowledge base like Wikipedia, users do not get to disagree on the shared content; it looks the same to everyone, and that forces convergence.  In our case, however, we have the option of including data sources in our graph which are not universally writable.  If John wants kickboxing under sports and Jane wants yoga, they can either add both kickboxing and yoga in the shared graph, or Jane can add yoga to her graph while John adds kickboxing to his graph.  If I have included John's personal-public graph and Jane's personal-public graph in my... graph configuration (basket?)... I will see both kickboxing and yoga.  If I decide I don't value Jane's or John's views on sports, I can filter one or both out.  We are pretty close to having this functionality already.
