### ISSUE TITLE
In node view, display a hint that a wiki note is attached to a node

### ISSUE THREAD

**Issue by montaropdf** [synchrony/smsn#60]
Hello,

I am currently playing with smsn and something that bother me, among other things, is the fact that there is no indication when a wiki note (i.e.: a multi-line text) is attached to a given node.

Is there something available for that, but not documented or is it a feature you would need to add?

**Comment by joshsh** [comment]
Hi @montaropdf. On the right-hand margin of the tree view, you should see two numeric columns: one shows the number of parents for the atom on each line and the other shows the number of children. When an atom has `@text` and no children, you will see a purple-highlighted box in place of the child count. When an atom has both `@text` and children, you will see the child count inside of a red-highlighted box. Of course, these features depend on color support in your Emacs client.

**Comment by montaropdf** [comment]
As for issue #59, it seems my configuration is at fault.

**Comment by joshsh** [comment]
OK. Let us know if simplifying your configuration does not fix the problem.
